<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Reqnroll.xunit.v3" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="WireMock.Net.Testcontainers" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Features\**\*.feature">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
